### ISSUE TITLE
项目运行不了了，有问题

### ISSUE THREAD

**Issue by AgentEric** [wwq123/RanchSearch#1]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. 

我看了代码，没发现在什么地方有问题，我觉得你写的这个项目还算工整，为什么不好好弄弄，维护下来呢

**Comment by wwq123** [comment]
你好，我刚刚用Xcode8在手机上运行这个项目(手机系统9.3.2),发现没有问题。后来在模拟器上(模拟器系统10.0.0)运行结果就出现你上述提出的问题。通过检查定位到崩溃的位置，是因为”[self.view.layer insertSublayer:radarView.layer atIndex:0]“这句代码。不知道为什么在10.0.0系统上这种写法会崩溃。我重新换了一种写法。如今问题被解决掉。谢谢你的意见

**Comment by AgentEric** [comment]
可以跟你学习一下，怎么定位到那句 Insertlayer 的吗？ 我的头像就是我的微信，方便的话可以加一下，亲。交个朋友，我是真的想虚心学习。

**Comment by wwq123** [comment]
其实我刚开始加了全局断点也没有定位到错误，再查看控制台输出的错误信息”Problem view: <WWQRadarView: 0x7f9938f04c00; frame = (0 0; 320 568); layer = <CALayer: 0x60000003b7c0>>
    Expected parent: <UIView: 0x7f9938c08b80; frame = (0 0; 320 568); autoresize = W+H; layer = <CALayer: 0x60000003b660>>“,错误信息说的是有问题的View是WWQRadarView(Problem view)，父视图的CALayer的内存地址是<CALayer: 0x60000003b660>。所以我想问题应该是出在WWQRadarView的layer的添加上。于是我去到了使用WWQRadarView的控制器中，屏蔽了添加WWQRadarView的layer的代码，发现不再出现闪退。

**Comment by AgentEric** [comment]
我在github上搜索“微信 雷达”，搜到了两个，还有一个[LRRadarTest](https://github.com/RomitLee/LRRadarTest)，里面代码大同小异，但是他没有你写的工整，所以我想和你一起不断完善这个项目，不断地优化，把这个项目做好一点，你觉得如何？我可以加你的微信吗？不乐意就算了，只是为了交流方便。

**Comment by wwq123** [comment]
可以的。我刚刚已经加你微信了，扫你头像的
